services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    env_file: .env
    image: nba-extractor-image

    # volumes:
    #   - /Users/minh.bo/Desktop/nba-data-pipeline/shared:/shared

networks:
  default:
    external: true
    name: airflow_default